# version format
version: 3.7.{build}

environment:
  #GIT_TRACE: 1
  access_token:
    secure: eWAovbJD8C/F5ObWegnOimwNFyeU1vXzW6lwbJzhHpSUgjT+CMexMcPUBMKrm+Wl
  psgallery_key:
    secure: FuPgJskczZMptxRgdUlBAy7OYmXBQl4zq86kXXSmBt6wKudnM2PK7W6cM7bj0te1
  coveralls_key:
    secure: 9FaqY8bTu/NyXmXKDGw3qDHe/JbyZPY6F1Y0NcJ9Yrm/m0qGVemONpUvLYn9Es2U
  github_email:
    secure: x5ljenzXfYXkzpEu9eX7AQvb3AkFbiXG2NndMzw9Zc4=
  #sig_key:
    #secure: LPEv2aGCLb1WPw89OFF8gmhk5tVZtOAPaUJ9cAATBnD1+qREYmvh/fH53NbJSNPD9sMryoTv+hwq+McL2sNw3WAnd5iAnKIN3gu34TFM21sYsA2UOSS7sNXXdkfjzLZlnqQlj9hmokNsbEbUQhPffRcX93HZ5ykrH+NKgc3AeYc20JfdLgqUzt/TYumPlw3DXtHbmAD3Pt8ZDW9VXEozGHzMCDRwCT+WnF4hhOa+mw6l82yqIJLYQSD9TTq8weANNAK3XZFpJZ6ssdyvzzS/q72FvNd5cw9wFpYvKudCFaaiqHP42l1QjuVMF1ocsRQA0fDMP/9VnysN4c8R2Url3daP7H6GCgXISfiNpiVcP4hKEUi0LZwFMfZ/OwF6IaHcZroZeVAr2UVfwAfrnFnWlQVE1vFJtFyXxbOHXGN0nNjcXQdIsLSX17ppTQPHfhlBpAcexp3mMfgZ5DDP0cwLmmQ5FubccoOJWTUB8+aKzxl6aaUn28xox2M11WPsTk/62KhJb8JZRiGayX7E5l9q6WIdTHRK5xV3fBA4FpPSgFBopp8K+zkEXedeKgC5lzemV+uchML76MQCWVn6JBl3RDlO6g5cNpNUsZ6xAxRuAaEAi64qzNcOroGuNdsx/4QeXz+YDwVrQZH1aBaSpY0w2oOiYjCObEVFuqiqlsn9ijfzNhJ09Ti2qp1KOqBogKRkeFD/160Sc3DWdWyaC7yakkNueK1Y73HIONMgt/pZLYanbJYUJgyvrNvpv3bzim5Q/E/xL1cRX3eQOEXJFmUxF/iyUPGFKWRPp+P2lEWBsNNwih1Pu9wz+wtCHqPLeU5sw3V075J+NXjBsEtPZtt++uDZdcRrGBcdyJoJgB356ln2s/xTDxCn3zEsZrSVwd0gxDUXx9aS/KRFvbNp4G3MlkmmZetQf7cdi6Hx6yiXbWWTPV0ljPxV6YWrOcoI+tshyRwbb2und7iLvvhlTrrCuyAwCsQFGAB+Dh3UPZjppjphEkl0eM4+mjvNpeqrPxMG21e8EVOZlsXSuxW9Plzz9aNMpg/CGB8nE0MUBOB+odemXh92m1DeAP4EBEG+X/N4qIHp9WAQc0D0XxBrwk03lByEPkJTUIADLjsm8DJGW8+PHjRfvo9awk9zPEJ4jlyS1/wZLM3PQcodT3COQmOEQ3BuzA82wXX5Af7T1typeAntkGgiVdC8FgYkrREkyLmtmzLaU3HC2YBOYZahmbbHoVXc+n4JNPf8BC4jaF2aozIhUfVDKaT5r/nvSQ42/XDTYXMPby5lDXqQmNEpDKn0BfqvxdMwwHeiuMef8GJKqXocHsmqKQNomLzJCqsgsSCoppflu7vilEglqPJ5Lonp14qSXmns2y27sS3SNjEIY84UCh01EBBk57jdcYnWEbhRGL3bQGSh2yPP81+Zo4HQ7jjpI7HNW6vxJWHSy+ndUW1d6DowOUMGDhpcpAQxg3Snxt7mfhqRVTXLoUBvWjNXOBpxVQHqjpEp+cV5/ov7vecMxenDLNSyHf5kQqzHnZ5Xr0y+g3bRgTm6xRrCvZV3SaUDoqFpOBXmruoLtQK3CpEiEf2t0XXhpJS/uAErEPHi90zfXQoC1+n1DNycITW9Kphz4vvZDf4/yf6dk8oZIOX27YsnmhYUGTrIuqZxquOgbYQln9P08rkwNT/jDHBiDDwDcGTGT4IfFSzr3njms9XBeLWUS0i3GM6ZzX9EynqBqOtRUEnMkTXJC2siMn5f04HeHB3v+XZM4VvfUv+HtBTt8HuALVyMGdxrvXsBW+dflqBBrjE6axWAqtNnRO2U9ozkHNbtrTogaUR3/gHRlVpYBAE26veJobQ9W9rEQHS0AyY4rYPvIECIG9IuNBGiH+CVP19BUqpdR9+mc1xjbKh73p2Kj8RiO2/eOy9aLzxzmjPqgkpvd6Ai5M9yhceufCXDkEwSl3JodFrooo115N52rp+rT7o/fz78KoRgKiKmMBYuPy3wuTVTR5iKiOZ/Ml/rnUuoxrNpwS5zVlYEoe+gfVNXoig58C33dhuxCJLg0hChRbYjNTy7ZfeCOuYGwv28RpST/x6U/GOZWpsvc8q3Zmy21FeTu6+bCXENVr0BhWak5lgJGmcllU2JVbhKvmcRXSgiy6LS1tlRT44dVWmzSlKdi1PDYtoL2DGyKQNYSLTDYc4x6UYP5lrPnzkSRaeyyNJ4UbOrxTZMJEj13CNC3a4wd/3c6eVYae2c/cDixoI0D0KyUercp8juQ+srrjYCwpz7cy20hHEi59Za8pJcUl6sGXUq9nJdw+JNmWplQ23o5I349gDpmEfHRvCloQnXAknA6SfV88+JpNAUaJ8/7nyKMXqMsaY1hJT8Bd9UqXVwfm0OvMTwPGg5Fd8dwGeKp6aJKvEfU9co+hbzZU1gc7mn0KGuxyf8zKJnQpiNjAvg4P6GpOEMZmB1GEzVrHb90oKmsBDHQtPNBQh3hVubvn9weETUvkrNiWN759OUoNiToleXj1lIuR+BMNqUXtmhV/bcaJAnEw4ut5zUlv7EMO2zc6LSk6t021xwzaMNUcOfp8nYlXgJIFlZUnio6NjzoP+O/bG9aTvSj4jCqsB+P+upB+CExeZTU6RCKABCw9nt96wxO2GHv7LPeQ/sZELSRtt5MiBRAx2JjrAR1FfoY5O9eV5zM+Jr/8Q+OqlD+EJahasgZWFVwDHHK2Jyb9b0vWjLWrpgQ5F/8QfNoQ9NnR/NuvSZZ/6wGNFzMgSGE0361qIf5Z3NcY11+OgSqOChVBR72sK3siwCF5tHLSJ6DuZ+MLAc/Rk1TdDMiQqqcahXm1pa1paIvzwEnt7N+Fh6cV8qfTFNVhqR4Hfcl/AH+Fi+din8YMVcXx1dxAwdCSunkCwv1qzA3N4LJwPaFHQf9wlNp4J+C0VkHfa+pDKy5gAH6/O6ECWvPgOt7wah03IXmDr/kQ5QL7E/vUmcaoxhNtSbr/Mt/C/akMswtfoobpbrJwnFG6GEI3qss6qBhzP42lc8ogGqpfJqEvVV6meSuXtxtZqD85VFPEqDnqiEsX8aET65bTjbxKBn6zXCuFlbJZLFVaRQyC/mnRHHmue/0wZaqvNbtYDFnrrHbYH8zzEdOhHqMuDISaS9v/iG3reC9tLdnscVhYdD7+qzb9HLdbWIHoxYMfXq8as3rInruCfRxyv7vqrdgE79Au7K/N+WH64SGzPpvznqfpSrhrqP57cGYuzaiJ3KmTk91we/9gCNrfJeeyJn03jluiRsL/z/GFTzhnfTTJ0McZWz4yWTgkac6U+7U1R4ynW3ybpc4TBNq1jHiT3nlCgmjX8FHJdfi6Yaq6aIYNLhibhLTJ5OPf8jZiak5rKOhh81+yi3Pq8o/vArY9JayTiP42UguE/0EU8lB9VArLsf7jBs7zTTrGNqcdA7LIg3V7DS9RH5+a0R0ALuByhi4/we4asDDYFzC1ou59PTzOSryJ1jgV5D6in0KLIWrm6lAn+JCIx3ozCUQ9oXRbfratirEKIlX4OTILhmjkghNHoH3QOeLbDFdZzWTwLxK/cZ3cbJnzds/9t2SgRT+kYkaE3O8OiKOg4TRWqx8P0nrG+KI1/YNUcpsWUMcMUxrYE7cvaU5doNiw0n5gCOJLW69cZDCocavR9ABdMu20DgHIPRTRyFwa3pip5d1aZ4PFRjVj3SzwXa6yqUa5+WOIqqOXDJNR5CnBIuto5I6TvcYv/rE58nRDnMWtVRlqUa3svJ1qUI/ShNnjddWSn+WAbMPrTuC2B80Y/R/ygAzOelTgmqurY8GiPDn9Kzwk8KmQLbzEMxjzKxZKCo4ccWa1FTt7pZPOq56+nxTvS+QF1TwKrcD4jY+s8tqissek5paTEH5ljf1LjMmkB9n2HSH/ECJKsAvLEmuNaJYQHjgBmYdf+mvFARuruM8lHo9hhcbKnQif7Jv+Nmbt9WdzxWe1X8/Vl1VbEr6S4q6UFp7+OJV5fxZEGdNy7qc/wr3Zm9940zC+JjJLNhGc/UEllmTCbHkXY4/iCWV4oQjq6Ddh/Ia6/j1BpoiWzMcmiR7I5A6TDsmBZpLaeC8Y4MZrv4p+jmg/T3OxAM9HXPonFLDG+3xPROhYTtOFiZdvxRE6tlMtgj2FXfhftOsY6OmqTvWnC4/VU0zz6aMMAaVLaZnW65FcWUmU74SqFWz5HeF2A3UDATCRjkdtHcFS76FRrBDFKsdKQGBgRs2ghX57nybDyjlVTOk9xz6P1MNckTZ3EmE/Gm/PzzPmNdNgG33BuafdhWUgZ9MdaGjIcVQUNh7ucxBhVfvHWZsUoV6h8oScW+7nZS/hQue1WOyRQwtvCGLPgSnPvdwl8f9PB7AneHvQ0PWR25iKZE+BHfc4gV3GpPSTG0dTeTwTmMuUEZQ8K1+/hRecF2Wb53bFda7QfkzR150rdLyX6TTiyWbHCkMWSDOKnwe+sv/vZy1ojyRf90t3SKwMZD8P7ljdkGRXE0NvcKER0vlw4eIshGxg1hOpM5UYj22S1/h6oAkuXZjWQhahahxCeD0Mowu64yYWLIGJkhWE5qD4q0wO2aqD534TZH71KsByAlrt3+65zVIgYr5F0HiadU3gly1mQ85tHi8ycd9f1mGVpsD4FXRY9baklVaW5NhZL8Uzg9UvhfdRhF2ousToYql9kvmFBARASA2HczwqmUPOuX+g==
  #PfxSecure:
    #secure: Kkp5iutKCw8ACijkd5Et8xUjF4e39dJRuoaTWIHem5tVaF5QeqUnrPSjkPsNDwro

skip_tags: true

skip_commits:
  files:
    - docs\*
    - .github\*
    - .vscode\*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - appveyor.yml
    - CHANGELOG.md
  message: /update readme.*|update version.*|update appveyor.*/

only_commits:
  files:
    - build\
    - CredentialRetriever\
    - tests\

image: Visual Studio 2019

install:
  #- ps: . .\build\install.ps1
  - pwsh.exe -File .\build\install.ps1

build_script:
  - pwsh.exe -File .\build\build.ps1

test_script:
  #- ps: . .\build\test.ps1
  - pwsh.exe -File .\build\test.ps1

deploy_script:
  - pwsh.exe -File .\build\deploy-github.ps1
  - pwsh.exe -File .\build\deploy-psgallery.ps1

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
