# version format
version: 3.1.{build}

environment:
  access_token:
    secure: eWAovbJD8C/F5ObWegnOimwNFyeU1vXzW6lwbJzhHpSUgjT+CMexMcPUBMKrm+Wl
  psgallery_key:
    secure: FuPgJskczZMptxRgdUlBAy7OYmXBQl4zq86kXXSmBt6wKudnM2PK7W6cM7bj0te1
  coveralls_key:
    secure: 9FaqY8bTu/NyXmXKDGw3qDHe/JbyZPY6F1Y0NcJ9Yrm/m0qGVemONpUvLYn9Es2U

skip_commits:
  files:
    - .github\*
    - .vscode\*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - appveyor.yml
    - CHANGELOG.md
  message: /update readme.*|update version.*|update appveyor.*/

only_commits:
  files:
    - build\
    - CredentialRetriever\
    - tests\

image: Visual Studio 2017

install:
  - pwsh.exe -File .\build\install.ps1

build_script:
  - pwsh.exe -File .\build\build.ps1

test_script:
  - pwsh.exe -File .\build\test.ps1

deploy_script:
  - pwsh.exe -File .\build\deploy.ps1